Make `LintRoller::Plugin` sortable
Typically, it is expected that `LintRoller::Plugin#about` includes a name,
and sorting would be performed based on that name. However, currently,
executing `sort` on LintRoller results in the following error:

```console
ArgumentError: comparison of LintRoller::PluginTest::SampleRoller with LintRoller::PluginTest::AnotherRoller failed
```

This PR makes `LintRoller::Plugin` sortable by name. I considered including the version as well,
but I could not come up with any use cases where multiple plugins with the same name would need to be processed simultaneously.